#!/usr/bin/env python3
# -*- coding: utf-8; -*-

# This is autogenerated python file DO NOT try to edit

import json

json_package_path = '../../../emoji.json'

data_dict = json.loads(open(json_package_path).read())

unicode_replace = {}
shortcode_replace = {}
ascii_replace = {}
category_replace = {}

for key, value in data_dict.items():
    unicode_hex = value['code_points']['base']
    ascii = value['ascii']
    shortname = value['shortname']
    if ascii:
        for item in ascii:
            ascii_replace[item] = unicode_hex
    shortcode_replace[shortname] = unicode_hex
    category_replace[shortname] = value['category']

    if '-' not in unicode_hex:
        unicode_char = chr(int(unicode_hex, 16))
        unicode_replace[unicode_char.encode('utf-8')] = shortname
    else:
        parts = unicode_hex.split('-')
        unicode_char = ''.join(chr(int(part, 16)) for part in parts)
        unicode_replace[unicode_char.encode('utf-8')] = shortname

f = open("ruleset.py", "w")

f.write('''#!/usr/bin/env python3
# -*- coding: utf-8; -*-

# This is autogenerated python file DO NOT try to edit

''')
f.write("unicode_replace = " + str(unicode_replace) + "\n")
f.write("shortcode_replace = " + str(shortcode_replace) + "\n")
f.write("ascii_replace = " + str(ascii_replace) + "\n")
f.write("category_replace = " + str(category_replace) + "\n")

f.close()